version: "3.4"

services:
  web:
    image: httpd:latest
    volumes:
      - ./web/bin:/usr/local/apache2/htdocs 
    ports:
      - 80:80
      
  db:
    image: questdb/questdb
    ports:
      - 9000:9000 # Web console / REST API
      - 9009:9009 # InfluxDb line protocol
      - 8812:8812 # Postgres wire protocol

  api:
    build: api
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:9000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "81:5000"
